import Image from "next/image";
import Hero from "@/components/Hero";
import Container from "@/components/Container";
import CTA from "@/components/CTA";
import {process} from "@/data/process";
import {BLUR_DATA_URL} from "@/lib/image";

export const metadata={title:"Proces budowy domu modułowego",description:"Pięć etapów budowy NORDHUS: od wyboru modelu i analizy działki po produkcję, montaż i odbiór.",openGraph:{title:"Proces budowy domu modułowego | NORDHUS",description:"Pięć etapów budowy NORDHUS: od wyboru modelu i analizy działki po produkcję, montaż i odbiór.",images:["/images/montaz.jpg"],type:"website"},twitter:{card:"summary_large_image",images:["/images/montaz.jpg"]}};
const images=["/images/hero.jpg","/images/montaz.jpg","/images/produkcja.jpg","/images/wnetrze-salon.jpg","/images/model-92.jpg"];

export default function Page(){return <>
 <Hero image="/images/montaz.jpg" alt="Montaż modułu NORDHUS" eyebrow="PROCES" title="Wiesz, co dzieje się dalej." text="Budowę dzielimy na pięć etapów. Każdy ma określony zakres, dokumenty, odpowiedzialność i orientacyjny czas."/>
 <section className="section-space"><Container><div className="max-w-[680px]"><p className="eyebrow text-[var(--sage)]">Harmonogram</p><h2 className="mt-5 text-[clamp(2rem,4vw,3.75rem)]">Od pierwszej rozmowy do odbioru.</h2><p className="mt-6 text-[1.0625rem] leading-[1.75] text-[color:rgba(28,28,26,.85)]">Standardowy harmonogram zakłada około 5 miesięcy od zamknięcia założeń do gotowego budynku. Formalności administracyjne, badania gruntu, przyłącza i niestandardowe wyposażenie mogą działać równolegle albo wydłużyć termin. Dlatego przed uruchomieniem produkcji oddzielamy terminy zależne od NORDHUS od terminów urzędowych i prac zewnętrznych.</p></div></Container></section>
 {process.map((x,idx)=><section key={x.number} className={`section-space overflow-hidden ${idx%2?"bg-[#f1f0eb]":""}`}><Container><div className="grid grid-cols-12 gap-y-10 lg:gap-x-8">
  <div className={`relative col-span-12 lg:col-span-7 ${idx%2?"lg:col-start-6 lg:row-start-1":""}`}><div className={`reveal-image relative aspect-[4/3] overflow-hidden ${idx%2?"lg:w-[calc(100%+max(0px,(100vw-1360px)/2))]":"lg:ml-[calc(-1*max(0px,(100vw-1360px)/2))] lg:w-[calc(100%+max(0px,(100vw-1360px)/2))]"}`}><Image src={images[idx]} alt={x.title} fill quality={90} className="object-cover" sizes="(min-width:1024px) 60vw,100vw" placeholder="blur" blurDataURL={BLUR_DATA_URL}/></div></div>
  <div className={`relative col-span-12 self-start lg:col-span-4 ${idx%2?"lg:col-start-1 lg:row-start-1":"lg:col-start-9"}`}><span aria-hidden="true" className="pointer-events-none absolute -left-3 -top-16 -z-10 text-[clamp(6rem,10vw,7.5rem)] font-extralight leading-none text-[var(--line)]">{String(x.number).padStart(2,"0")}</span><p className="eyebrow text-[var(--sage)]">{x.duration}</p><h2 className="mt-5 text-[clamp(2rem,4vw,3.75rem)]">{x.title}</h2><p className="mt-4 font-medium">{x.result}</p><div className="mt-7 space-y-5">{x.details.map((p,i)=><p key={i} className="max-w-[66ch] text-[1.0625rem] leading-[1.75] text-[color:rgba(28,28,26,.85)]">{p}</p>)}</div></div>
 </div></Container></section>)}
 <section className="section-space"><Container><div className="grid grid-cols-12 gap-y-10"><div className="col-span-12 lg:col-span-4"><p className="eyebrow text-[var(--sage)]">Płatności</p><h2 className="mt-5 text-[clamp(2rem,4vw,3.75rem)]">Transze powiązane z etapami.</h2></div><div className="col-span-12 overflow-x-auto lg:col-span-7 lg:col-start-6"><table className="w-full min-w-[720px]"><thead><tr className="border-b border-[var(--ink)]"><th className="py-4 text-left">Transza</th><th className="text-left">Moment</th><th className="text-left">Udział</th><th className="text-left">Co zamyka etap</th></tr></thead><tbody>{[["1","podpisanie umowy","10%","rezerwacja terminu i start projektu"],["2","zatwierdzenie projektu","25%","zamówienia materiałowe"],["3","start produkcji","35%","uruchomienie modułów na hali"],["4","gotowość do transportu","25%","odbiór produkcyjny"],["5","odbiór końcowy","5%","protokół i dokumentacja"]].map(r=><tr key={r[0]} className="border-b border-[var(--line)]">{r.map((v,i)=><td key={v} className={`py-5 pr-5 ${i?"text-[var(--muted)]":"font-medium"}`}>{v}</td>)}</tr>)}</tbody></table></div></div></Container></section>
 <CTA/>
 </>}