"use client";
import Link from "next/link";
import {useEffect,useState} from "react";

const voiv=["dolnośląskie","kujawsko-pomorskie","lubelskie","lubuskie","łódzkie","małopolskie","mazowieckie","opolskie","podkarpackie","podlaskie","pomorskie","śląskie","świętokrzyskie","warmińsko-mazurskie","wielkopolskie","zachodniopomorskie"];

function Field({label,name,type="text",error}){
 return <div className="form-field"><input id={name} name={name} type={type} placeholder=" " aria-invalid={!!error} className="form-control peer"/><label htmlFor={name} className="form-label">{label}</label>{error&&<p className="form-error">{error}</p>}</div>
}
function Select({label,name,options,value,onChange}){
 const props=value!==undefined?{value,onChange}:{defaultValue:""};
 return <label className="block"><span className="form-select-label">{label}</span><select name={name} required className="form-select" {...props}><option value="">Wybierz</option>{options.map(x=><option key={x}>{x}</option>)}</select></label>
}
export default function ContactForm(){
 const[modelValue,setModelValue]=useState(""),[errors,setErrors]=useState({}),[sent,setSent]=useState(false),[notes,setNotes]=useState("");
 useEffect(()=>{setModelValue(new URLSearchParams(window.location.search).get("model")||"")},[]);
 function submit(e){e.preventDefault();const f=new FormData(e.currentTarget),next={};if(!f.get("name")?.trim())next.name="Podaj imię i nazwisko.";const email=f.get("email")?.trim();if(!email)next.email="Podaj adres e-mail.";else if(!/^\S+@\S+\.\S+$/.test(email))next.email="Sprawdź poprawność adresu e-mail.";if(!f.get("phone")?.trim())next.phone="Podaj numer telefonu.";if(!f.get("rodo"))next.rodo="Zaznacz zgodę, aby wysłać formularz.";setErrors(next);if(Object.keys(next).length)return;console.log("NORDHUS demo form:",Object.fromEntries(f.entries()));setSent(true)}
 if(sent)return <div className="reveal-in border-t border-[var(--line)] py-10 opacity-100 transition-opacity duration-700"><p className="eyebrow text-[var(--sage)]">Dziękujemy</p><h2 className="mt-5 text-[clamp(2rem,4vw,3.75rem)]">Zapytanie jest gotowe.</h2><p className="mt-6 max-w-[62ch] text-[1.0625rem] leading-[1.75] text-[color:rgba(28,28,26,.85)]">To wersja demonstracyjna. Dane nie zostały wysłane na serwer. W rzeczywistym procesie opiekun projektu odpowiada w ciągu 24 godzin w dni robocze i prosi o numer działki albo link do mapy.</p><Link href="/modele" className="text-link mt-8 inline-block font-medium">Zobacz modele →</Link></div>;
 return <form onSubmit={submit} noValidate className="space-y-16">
  <fieldset><legend><span className="eyebrow text-[var(--sage)]">01</span><span className="ml-4 text-2xl font-medium">Kontakt</span></legend><div className="mt-9 grid gap-8"><Field label="Imię i nazwisko" name="name" error={errors.name}/><Field label="E-mail" name="email" type="email" error={errors.email}/><Field label="Telefon" name="phone" type="tel" error={errors.phone}/></div></fieldset>
  <fieldset className="border-t border-[var(--line)] pt-10"><legend><span className="eyebrow text-[var(--sage)]">02</span><span className="ml-4 text-2xl font-medium">Twój dom</span></legend><div className="mt-9 grid gap-8 md:grid-cols-2"><Select label="Interesujący model" name="model" value={modelValue} onChange={e=>setModelValue(e.target.value)} options={["NORDHUS 68","NORDHUS 92","NORDHUS 124","NORDHUS 156","Jeszcze nie wiem"]}/><Select label="Metraż docelowy" name="area" options={["do 80 m²","80–110 m²","110–140 m²","powyżej 140 m²"]}/><Select label="Budżet" name="budget" options={["do 600 tys. zł","600–900 tys. zł","900 tys.–1,2 mln zł","powyżej 1,2 mln zł"]}/><Select label="Województwo" name="voivodeship" options={voiv}/></div><div className="mt-9"><p className="form-select-label">Działka</p><div className="mt-4 flex flex-wrap gap-6">{["Mam działkę","Jestem w trakcie zakupu","Szukam"].map(x=><label key={x} className="text-sm"><input required type="radio" name="plot" value={x} className="mr-2 accent-[var(--ink)]"/>{x}</label>)}</div></div></fieldset>
  <fieldset className="border-t border-[var(--line)] pt-10"><legend><span className="eyebrow text-[var(--sage)]">03</span><span className="ml-4 text-2xl font-medium">Szczegóły</span></legend><div className="mt-9 grid gap-8 md:grid-cols-2"><Select label="Planowany start budowy" name="start" options={["do 3 mies.","3–6 mies.","6–12 mies.","później"]}/><div><p className="form-select-label">Finansowanie</p><div className="mt-4 flex flex-col gap-3">{["Gotówka","Kredyt","Kredyt w trakcie"].map(x=><label key={x} className="text-sm"><input required type="radio" name="financing" value={x} className="mr-2 accent-[var(--ink)]"/>{x}</label>)}</div></div></div><label className="mt-9 block"><span className="form-select-label">Dodatkowe uwagi</span><textarea name="notes" rows="5" maxLength={1000} value={notes} onChange={e=>setNotes(e.target.value)} className="form-select resize-none"/><span className="mt-2 block text-left text-xs text-[var(--muted)]">{notes.length}/1000</span></label></fieldset>
  <label className="flex items-start gap-3 text-sm"><input type="checkbox" name="rodo" className="mt-1 accent-[var(--ink)]"/><span>Wyrażam zgodę na wykorzystanie podanych danych w celu odpowiedzi na moje zapytanie.</span></label>{errors.rodo&&<p className="form-error -mt-12">{errors.rodo}</p>}
  <button className="btn-sweep focus-ring h-[60px] w-full bg-[var(--ink)] px-6 text-sm font-semibold text-white" type="submit"><span>Wyślij zapytanie</span></button>
  <p className="text-xs text-[var(--muted)]">Wersja demonstracyjna — formularz nie przesyła danych na serwer.</p>
 </form>
}