import Container from "@/components/Container";
export const metadata={title:"Polityka prywatności",description:"Demonstracyjna polityka prywatności i informacja RODO serwisu NORDHUS."};
export default function Page(){return <section className="section-space"><Container><div className="mx-auto max-w-[720px]"><p className="eyebrow text-[var(--sage)]">RODO / dane demonstracyjne</p><h1 className="display mt-5 text-5xl md:text-7xl">Polityka prywatności.</h1><p className="mt-7 text-lg leading-8 text-[var(--muted)]">Poniższa treść jest wzorem do projektu demonstracyjnego. Dane administratora, adres, e-mail i telefon są przykładowe i przed użyciem na rzeczywistej stronie muszą zostać zastąpione prawdziwymi danymi firmy oraz zweryfikowane prawnie.</p>
<div className="mt-14 space-y-12 leading-8 text-[var(--muted)]">
<section><h2 className="text-2xl font-medium text-[var(--ink)]">1. Administrator danych</h2><p className="mt-4">Administratorem danych osobowych w przykładowym serwisie jest NORDHUS Sp. z o.o. — dane demonstracyjne: ul. Przykładowa 12, 00-000 Warszawa, NIP 000-000-00-00, e-mail: kontakt@nordhus-demo.pl, tel. +48 000 000 000. Podane dane nie identyfikują rzeczywistego przedsiębiorcy.</p></section>
<section><h2 className="text-2xl font-medium text-[var(--ink)]">2. Jakie dane mogą być przetwarzane</h2><p className="mt-4">Formularz kontaktowy może obejmować imię i nazwisko, adres e-mail, numer telefonu, województwo, informacje o działce, planowany model i metraż, budżet, termin inwestycji, sposób finansowania oraz treść wiadomości. W obecnej wersji demonstracyjnej formularz nie wysyła danych do serwera — po poprawnej walidacji są one wyłącznie wypisywane w console.log przeglądarki.</p></section>
<section><h2 className="text-2xl font-medium text-[var(--ink)]">3. Cele i podstawy prawne</h2><p className="mt-4">W rzeczywistym wdrożeniu dane z formularza mogą być przetwarzane w celu odpowiedzi na zapytanie i podjęcia działań przed zawarciem umowy na podstawie art. 6 ust. 1 lit. b RODO. Jeżeli kontakt nie prowadzi bezpośrednio do umowy, podstawą może być prawnie uzasadniony interes administratora polegający na prowadzeniu korespondencji i obsłudze zapytań, zgodnie z art. 6 ust. 1 lit. f RODO. Dodatkowe cele marketingowe wymagają odrębnej podstawy i odpowiedniego komunikatu.</p></section>
<section><h2 className="text-2xl font-medium text-[var(--ink)]">4. Okres przechowywania</h2><p className="mt-4">Dane związane z zapytaniem powinny być przechowywane przez okres potrzebny do obsługi kontaktu i przygotowania oferty. Jeżeli dojdzie do zawarcia umowy, część danych może być przechowywana dłużej w zakresie wymaganym przepisami podatkowymi, rachunkowymi i dotyczącymi dochodzenia lub obrony roszczeń. W rzeczywistym wdrożeniu administrator powinien określić konkretne okresy retencji.</p></section>
<section><h2 className="text-2xl font-medium text-[var(--ink)]">5. Odbiorcy danych</h2><p className="mt-4">Dane mogą być przekazywane podmiotom obsługującym hosting, pocztę elektroniczną, system CRM, księgowość albo wsparcie techniczne — wyłącznie w zakresie potrzebnym do świadczenia usługi i na podstawie odpowiednich umów. Lista rzeczywistych dostawców powinna zostać uzupełniona po wdrożeniu infrastruktury produkcyjnej.</p></section>
<section><h2 className="text-2xl font-medium text-[var(--ink)]">6. Przekazywanie poza EOG</h2><p className="mt-4">Jeżeli używany dostawca przetwarza dane poza Europejskim Obszarem Gospodarczym, administrator musi wskazać podstawę transferu, np. decyzję stwierdzającą odpowiedni stopień ochrony albo standardowe klauzule umowne. W wersji demonstracyjnej nie konfigurujemy zapisu danych z formularza.</p></section>
<section><h2 className="text-2xl font-medium text-[var(--ink)]">7. Prawa osoby, której dane dotyczą</h2><p className="mt-4">Osoba, której dane dotyczą, może żądać dostępu do danych, ich sprostowania, usunięcia lub ograniczenia przetwarzania, a w przypadkach przewidzianych przepisami również przeniesienia danych. Jeżeli podstawą przetwarzania jest prawnie uzasadniony interes, można wnieść sprzeciw. Gdy przetwarzanie odbywa się na podstawie zgody, zgodę można wycofać bez wpływu na zgodność z prawem wcześniejszego przetwarzania.</p></section>
<section><h2 className="text-2xl font-medium text-[var(--ink)]">8. Skarga do organu nadzorczego</h2><p className="mt-4">Jeżeli użytkownik uważa, że jego dane są przetwarzane niezgodnie z prawem, może złożyć skargę do Prezesa Urzędu Ochrony Danych Osobowych. Przed złożeniem skargi może również skontaktować się bezpośrednio z administratorem w celu wyjaśnienia sprawy.</p></section>
<section><h2 className="text-2xl font-medium text-[var(--ink)]">9. Dobrowolność podania danych</h2><p className="mt-4">Podanie danych w formularzu jest dobrowolne, ale pola oznaczone jako wymagane są potrzebne do przygotowania odpowiedzi. Brak danych kontaktowych uniemożliwia odpowiedź, a brak informacji o działce lub budżecie może ograniczyć możliwość przygotowania wstępnej analizy inwestycji.</p></section>
<section><h2 className="text-2xl font-medium text-[var(--ink)]">10. Pliki cookies i analityka</h2><p className="mt-4">Jeżeli strona wykorzystuje wyłącznie techniczne mechanizmy potrzebne do jej działania, należy opisać ich zakres. Jeżeli w przyszłości zostaną dodane narzędzia analityczne, reklamowe albo osadzone usługi stron trzecich, polityka powinna zostać uzupełniona o ich nazwy, okres działania, podstawę prawną i sposób zarządzania zgodami.</p></section>
<section><h2 className="text-2xl font-medium text-[var(--ink)]">11. Zautomatyzowane decyzje</h2><p className="mt-4">W demonstracyjnej wersji serwisu dane nie są wykorzystywane do zautomatyzowanego podejmowania decyzji ani profilowania wywołującego skutki prawne lub podobnie istotnie wpływającego na użytkownika.</p></section>
<section><h2 className="text-2xl font-medium text-[var(--ink)]">12. Zmiany polityki</h2><p className="mt-4">Polityka powinna być aktualizowana, gdy zmienia się sposób zbierania danych, dostawcy usług, zakres formularzy albo przepisy. Data obowiązywania rzeczywistej wersji dokumentu powinna być widoczna na początku lub końcu strony.</p></section>
</div></div></Container></section>}