import Container from "@/components/Container";import CTA from "@/components/CTA";
export const metadata={title:"FAQ — pytania o domy modułowe",description:"Odpowiedzi na najczęstsze pytania o działkę, formalności, ceny, kredyt, transport, montaż, gwarancję i technologię NORDHUS.",openGraph:{title:"FAQ — pytania o domy modułowe | NORDHUS",description:"Odpowiedzi na najczęstsze pytania o działkę, formalności, ceny, kredyt, transport, montaż, gwarancję i technologię NORDHUS.",images:["/images/hero.jpg"],type:"website"},twitter:{card:"summary_large_image",title:"FAQ — pytania o domy modułowe | NORDHUS",description:"Odpowiedzi na najczęstsze pytania o działkę, formalności, ceny, kredyt, transport, montaż, gwarancję i technologię NORDHUS.",images:["/images/hero.jpg"]}};
const items=[
["Czy dom modułowy wymaga pozwolenia na budowę?","Sam sposób prefabrykacji nie zwalnia automatycznie z formalności. Dla całorocznego domu jednorodzinnego procedura zależy od parametrów budynku, działki i aktualnych przepisów. Przed projektem architekt sprawdza MPZP albo warunki zabudowy oraz właściwy tryb administracyjny."],
["Czy każdy model da się postawić na każdej działce?","Nie. Znaczenie mają linie zabudowy, odległości od granic, szerokość działki, ukształtowanie terenu i dojazd transportu. NORDHUS 92 w literę L wymaga innej geometrii parceli niż piętrowy NORDHUS 124."],
["Jak sprawdzacie dojazd dla modułów?","Analizujemy szerokość drogi, promienie skrętu, ograniczenia tonażowe, gałęzie i linie napowietrzne. Na miejscu sprawdzamy również przestrzeń dla dźwigu. Jeżeli ostatni odcinek trasy jest problematyczny, planujemy dodatkowe zabezpieczenie albo inny sposób organizacji montażu."],
["Czy mogę zmienić układ pomieszczeń?","Tak, przede wszystkim ściany działowe, funkcje pokoi, układ kuchni i wybrane otwory. Zmiany w konstrukcji nośnej, dużych przeszkleniach i pionach instalacyjnych wymagają ponownego sprawdzenia. Ich wpływ na cenę pokazujemy przed zatwierdzeniem projektu wykonawczego."],
["Ile trwa cały proces?","W wariancie standardowym zakładamy około 5 miesięcy od zamknięcia założeń do odbioru. Projekt zajmuje zwykle 4–6 tygodni, produkcja 8–10 tygodni, a montaż konstrukcji 3–5 dni. Formalności, fundament i przyłącza mogą wydłużyć cały kalendarz."],
["Czy naprawdę montaż trwa tylko kilka dni?","Tak krótki termin dotyczy ustawienia i połączenia prefabrykowanych modułów na przygotowanym fundamencie. Nie oznacza, że cała inwestycja od pierwszej rozmowy do odbioru trwa kilka dni. Po montażu pozostają uruchomienia, odbiory i ewentualne drobne prace końcowe."],
["Co dokładnie obejmuje cena domu?","Zakres bazowy obejmuje konstrukcję, izolację, stolarkę, instalacje wewnętrzne, ogrzewanie, wentylację, bazowe wykończenie, transport w określonym promieniu i montaż modułów. Osobno rozliczany jest m.in. fundament, przyłącza zewnętrzne i zagospodarowanie terenu. Każda oferta ma tabelę zakresu, żeby dało się porównać koszt na tych samych zasadach."],
["Czy fundament jest w cenie?","Nie w cenie bazowej modelu. Fundament zależy od gruntu, spadku terenu i rozwiązań projektowych dla konkretnej działki. Po badaniu geotechnicznym można dobrać odpowiedni wariant i przygotować osobną wycenę."],
["Jak wygląda finansowanie kredytem?","Harmonogram płatności można podzielić na transze związane z etapami: umowa, projekt wykonawczy, start produkcji, gotowość do transportu i odbiór. Bank może wymagać własnej kolejności wypłat i dokumentów potwierdzających postęp. Dlatego harmonogram finansowy ustalamy przed startem produkcji."],
["Czy mogę zobaczyć dom przed zamówieniem?","W projekcie demonstracyjnym nie prowadzimy rzeczywistych wizyt inwestorów. W realnym procesie firma może organizować wizyty w domu pokazowym albo na wybranych realizacjach za zgodą właścicieli. Na stronie wszystkie obrazy są wizualizacjami demonstracyjnymi."],
["Jak działa gwarancja?","Gwarancja powinna rozdzielać odpowiedzialność za konstrukcję, elementy wykończenia i urządzenia producentów. Okresy oraz warunki serwisowe muszą wynikać z umowy i kart gwarancyjnych. Dane gwarancyjne pokazywane w tym serwisie mają charakter przykładowy."],
["Czy dom można rozbudować później?","Teoretycznie modułowa konstrukcja ułatwia planowanie zmian, ale nie zakładamy automatycznie możliwości dostawienia kolejnego modułu do każdego domu. Rozbudowa wymaga ponownego sprawdzenia konstrukcji, instalacji, fundamentu oraz formalności. Najlepiej uwzględnić taki scenariusz już w pierwszym projekcie."],
["Jakie ogrzewanie stosujecie?","Standard demonstracyjny zakłada pompę ciepła powietrze–woda i wodne ogrzewanie podłogowe. Moc urządzenia dobiera się z obliczeń dla konkretnego domu i lokalizacji. Nie dobieramy pompy wyłącznie po powierzchni użytkowej."],
["Czy jest rekuperacja?","Tak, w bazowym wariancie pokazujemy wentylację mechaniczną z odzyskiem ciepła. Trasy kanałów projektujemy przed produkcją modułów, dzięki czemu nie trzeba później szukać miejsca na kanały w gotowym wnętrzu."],
["Na jakim obszarze Polski działa NORDHUS?","Wersja demonstracyjna zakłada obsługę wszystkich 16 województw. Transport do 250 km od przykładowej hali jest zawarty w bazowym zakresie, a dalsza trasa wymaga osobnej kalkulacji. Cena zależy od liczby modułów, ograniczeń drogowych i liczby kursów."],
["Czy cena może się zmienić po podpisaniu umowy?","Zakres i cena powinny zostać zamknięte przed produkcją. Zmiana może wynikać z decyzji klienta, dodatkowych prac na działce albo sytuacji, której nie dało się wcześniej zweryfikować bez badań. Takie elementy powinny być opisane w umowie i zatwierdzone przed wykonaniem dodatkowych prac."]
];
export default function Page(){const faqJsonLd={"@context":"https://schema.org","@type":"FAQPage",mainEntity:items.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))};return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqJsonLd)}}/><section className="section-space border-b border-[var(--line)]"><Container><p className="eyebrow text-[var(--sage)]">FAQ</p><h1 className="display mt-5 max-w-4xl text-5xl md:text-7xl">Pytania, które warto zadać przed wyborem domu modułowego.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-[var(--muted)]">Odpowiedzi dotyczą demonstracyjnego procesu NORDHUS. Formalności, parametry działki i rozwiązania techniczne zawsze trzeba potwierdzić dla konkretnej inwestycji.</p></Container></section><section className="section-space"><Container><div className="mx-auto max-w-[720px]">{items.map(([q,a],i)=><article key={q} className="border-t border-[var(--line)] py-7"><p className="text-sm text-[var(--muted)]">{String(i+1).padStart(2,"0")}</p><h2 className="mt-3 text-2xl font-medium">{q}</h2><p className="mt-4 leading-8 text-[var(--muted)]">{a}</p></article>)}</div></Container></section><CTA title="Masz pytanie dotyczące konkretnej działki?" text="Wyślij numer działki, planowany metraż i budżet. Wstępnie wskażemy, które kwestie trzeba sprawdzić przed wyceną."/></>}